### ISSUE TITLE
csv comes with different suffix

### ISSUE THREAD

**Issue by napjon** [blaze/blaze#1011]
Hi, thank you for creating blaze, it's really awesome!

I have a bit request. I have large chunk of log files. And usually it ends with *.log.gz suffix. It isn't hard to change the name, but it would be nice if there's parameter that tells Blaze that it's actually a CSV file. That way, Blaze knows how to act based on that parameter.

**Comment by mrocklin** [comment]
You can wrap the filename in `blaze.CSV`

    d = blaze.Data(blaze.CSV('myfile.log.gz'))

The magic handling of string URIs is pleasant but, as you point out, prone to failure.  There are explicit versions like `CSV` just beneath the surface.

**Comment by mrocklin** [comment]
Oh, if you have many of these then you'll also want to use `chunks`

    d = blaze.Data(blaze.chunks(blaze.CSV)('*.log.gz'))

**Comment by cpcloud** [comment]
I wonder if something like

```python
logs = resource('*.csv', cls=blaze.chunks(blaze.CSV))
```
might be a nice release valve for patterns we don't implement.

**Comment by jonhari** [comment]
Thanks. My log files is tab separated, and has no column names. Where should I put the parameter?  I've tried all of the above code:

    d = blaze.Data(blaze.CSV('myfile.log.gz',sep='\t'))

gives me:

```Python
.........


/Users/jon/anaconda/lib/python2.7/site-packages/networkx/classes/graph.pyc in __getitem__(self, n)
    317         {1: {}}
    318         """
--> 319         return self.adj[n]
    320 
    321 

KeyError: <class 'odo.backends.csv.CSV'>
```

This works however, d and d.shape spits out, but d.head() is error, same as the error above.

    d = bz.Data(bz.CSV('myfile.log.gz',sep='\t'),columns=names)
   
While the second code,
    
```Python

d = blaze.Data(blaze.chunks(blaze.CSV)('*.log.gz'))

/Users/jon/anaconda/lib/python2.7/site-packages/odo/chunks.pyc in discover_chunks(c, **kwargs)
     48 @discover.register(Chunks)
     49 def discover_chunks(c, **kwargs):
---> 50     return var * discover(first(c)).subshape[0]

AttributeError: 'String' object has no attribute 'subshape'

```

The third code,

```Python
logs = resource('*.log.gz', cls=blaze.chunks(blaze.CSV))
blaze.Data(logs)
```

This works, but then I don't know where to put column names and sep parameters. How do I do this?

**Comment by cpcloud** [comment]
@jonhari FYI, if this code works:

```python
resource('*.log.gz', cls=blaze.chunks(blaze.CSV))
```
then that's accidental. I was suggesting that we implement that as a way to do what you want. It is *not* implemented right now.
