### ISSUE TITLE
Migration to the Blaze organization

### ISSUE THREAD

**Issue by chdoig** [blaze/blaze#1132]
This is an issue to discuss, plan and list tasks involved in the migration of the repository from ContinuumIO to the Blaze Organization - https://github.com/blaze.

Instructions to transfer a repository here: https://help.github.com/articles/how-to-transfer-a-repository

**Comment by cpcloud** [comment]
@chdoig is there a specific date by which this needs to happen?

**Comment by mrocklin** [comment]
In my mind this is possibly lower priority than a few other things.

**Comment by cpcloud** [comment]
indeed it is, just trying to get a timeline

**Comment by chdoig** [comment]
I think it would be ideal to have them for Scipy - July 6th for message consistency, but I don't want to put any of our projects at risk.

**Comment by chdoig** [comment]
Is there anything we should have in mind/check/do before we transfer it? I checked Bokeh's list when they migrated, but I don't think any of those apply to us:

https://github.com/bokeh/bokeh/issues/999

**Comment by cpcloud** [comment]
there'd probably be some URL breakage, but i can't think of any examples ATM

**Comment by bryevdv** [comment]
FWIW Bokeh migration was almost completely painless.
