### ISSUE TITLE
Test failures with dask >= 0.7

### ISSUE THREAD

**Issue by cournape** [blaze/blaze#1234]
Not sure whether this is a dask or blaze issue, but I see this with dask 0.7.0 and blaze 0.8.2:

```
              raise NotImplementedError("Don't know how to compute:\n"
                      "expr: %s\n"
  >                   "data: %s" % (expr3, scope4))
  E           NotImplementedError: Don't know how to compute:
  E           expr: x[:, None, :]
  E           data: {x: dask.array<from-array-17197109b6550c08e29ea52cc14bc242, shape=(4, 5), chunks=((2, 2), (2, 2, 1)), dtype=int64>}

  ../../../build/master-env/lib/python2.7/site-packages/blaze/compute/core.py:191: NotImplementedError
```

Pretty much every test in `test_dask.y` fails in a similar way.

**Comment by cpcloud** [comment]
I'm running against dask master and blaze master and there are no failures of this kind

**Comment by cpcloud** [comment]
Can you try against master on both and see if the issue still persists?

**Comment by cournape** [comment]
Trying to run blaze tests from master gives me many errors related to odo (even though I am using the latest odo release, 0.3.3):

```
_________________________________________________________________ ERROR collecting blaze/tests/test_utils.py _________________________________________________________________
../../buildsystem-git/build/master-env/lib/python2.7/site-packages/py/_path/local.py:629: in pyimport
    __import__(pkgpath.basename)
blaze/__init__.py:19: in <module>
    from .expr import (Symbol, TableSymbol, symbol, ndim, shape)
blaze/expr/__init__.py:4: in <module>
    from .expressions import *
blaze/expr/expressions.py:10: in <module>
    from odo.utils import copydoc
E   ImportError: cannot import name copydoc
```

FWIW, I see the same errors originally reported using conda :) (I did `conda create -n test blaze dask pytest`).

**Comment by cpcloud** [comment]
If you're getting that error then you're not running against odo master. Your `test` environment odo will be the most recent release which is incompatible with blaze master.

**Comment by cpcloud** [comment]
```sh
# get blaze and dask dependencies
conda create -n test blaze dask && conda remove -n test blaze blaze-core odo dask
# clone blaze, odo, dask
# python setup.py develop in each of the above
```

**Comment by cournape** [comment]
Thanks for the instructions, but I am just trying to find a set of compatible released versions (since I am interested in packaging blaze). Until a fix is released, looks like I will have to keep dask to `0.6.0` (dask `0.6.0` works w/ blaze `0.8.2` and odo `0.3.3` from the test suite POV).

**Comment by mrocklin** [comment]
One can always depend on the versions tagged in the last anaconda release.  Those are always tested together.

**Comment by cournape** [comment]
Good to know @mrocklin, I will keep that in mind when updating packages in the blaze ecosystem.
