### ISSUE TITLE
How to process the missing value?

### ISSUE THREAD

**Issue by kwin-wang** [blaze/blaze#1236]
I want to filter some record containing missing value,  so In SQL:

```sql
select * from my_table  where  one_column is not null
```
, and In `Pandas`:

```python
df_new = df[df.one_column.notnull()]
```

but, how to process the missing value by Blaze ?

thanks!

kwin

**Comment by kwin-wang** [comment]
I haven't find the same api like `isnull()` or `notnull` or `isnan`...eg

**Comment by llllllllll** [comment]
We recently added a `notnull` operator, for example:

```python
In [1]: ds = bz.Data('postgresql://localhost/test::test')

In [2]: ds
Out[2]: 
    a
0   1
1 NaN
2   2
3 NaN
4   3

In [3]: ds.a.notnull()
Out[3]: 
       a
0   True
1  False
2   True
3  False
4   True

In [4]: ds[ds.a.notnull()]
Out[4]: 
   a
0  1
1  2
2  3

In [5]: ds[~ds.a.notnull()]
Out[5]: 
      a
0  None
1  None
```

Here you can see that we chose to not add an `isnull`, and instead, you can negate the `notnull` using the unary not operator `~`. This will be available when we release 0.8.3 or you can get access to this feature by installing from master.

**Comment by llllllllll** [comment]
Hey, were you able to get this working?

**Comment by kwin-wang** [comment]
thanks for your reply!


I convert the expression object to Pandas DataFrame object by odo library
of Blaze, then processing the missing value by Pandas way


 for the statbility of my project ,   I haven't  install the latest version
by source code until the stability version of Blaze released  on condo repo.


kwin.wang

2015-09-15 10:33 GMT+08:00 Joe Jevnik <notifications@github.com>:

**Comment by llllllllll** [comment]
Awesome, thank you.
