### ISSUE TITLE
?string join with string fails

### ISSUE THREAD

**Issue by cpcloud** [blaze/blaze#1241]

**Comment by cpcloud** [comment]
@llllllllll I believe this is happening when promoting to object. Long term it would probably be best to not use numpy for promotion, short term we can special case strings.

**Comment by llllllllll** [comment]
Yeah, the failure mode is that I am checking if `promote(a, b) != object_` because I assumed that meant that no promotion was found. I agree with both rolling our own promotion function and special casing strings for now

**Comment by kwmsmith** [comment]
Closed by #1478.
