### ISSUE TITLE
memoize dshape 

### ISSUE THREAD

**Issue by llllllllll** [blaze/blaze#1245]
I had a pretty large expression which I wanted to construct a predicate to select from.
It took 0.5 seconds to just construct the actual expression (without any computation), and running under cProfile showed that the time was dominated by access of the dshape/schema attributes. I think that we should memoize these properties because the expressions are immutable. If the expressions are weakreferencable, we could even slip an `@memoize(cache=WeakKeyDictionary())` between the getter and the property decorator

**Comment by cpcloud** [comment]
@llllllllll can this be closed?

**Comment by cpcloud** [comment]
closing as this was fixed already
