### ISSUE TITLE
blaze.__version__ returns "unknown"

### ISSUE THREAD

**Issue by canavandl** [blaze/blaze#1248]
blaze's version special method is unset and returns unknown

python 2.7
numpy 1.9

```python
import blaze
blaze.__version__
>> "unknown"
```

**Comment by cpcloud** [comment]
can you show `conda list blaze`?

**Comment by canavandl** [comment]
```bash
>> conda list blaze
# packages in environment at /Users/lcanavan/anaconda3/envs/proj:
#
blaze                     0.8.2                np19py27_0
blaze-core                0.8.2                np19py27_0
```

it the __version__ special method works (for me) for blaze=0.8.0

**Comment by cpcloud** [comment]
This is fixed in master, can you try there?

**Comment by canavandl** [comment]
Yes, it works in master. I'll close the issue.

thanks

**Comment by cpcloud** [comment]
Thanks for the report!


--
Best,
Phillip Cloud
