### ISSUE TITLE
map(...) from multiple columns

### ISSUE THREAD

**Issue by bittlingmayer** [blaze/blaze#1250]
The function passed as the first argument to `map` naturally only receives the value from one column as an argument.
```
d['x'].map(fn, 'string')
```
But suppose that I want a new column, `d['z']`, that is some arbitrary result of `d['x']` and `d['y']` (like appending them then lowercasing).  What is an elegant way to do this currently?  (Do I understand correctly that I should do this in Pandas?)

My preferred solution would be something like 
```
d['z'] = map(d['x'], d['y'], fn, 'string')
```

Note that for basic operations with ints, one can get around this using `transform`.
```
transform(d, z = d.x + d.z)
```
But for a string-type column that would give an error `AttributeError: 'Map' object has no attribute '_add'
`.  Thus one partial solution is to define the basic operations `_add`, `_sub` for all types, including string, or to allow users to easily define them.

**Comment by cpcloud** [comment]
@bittlingmayer Thanks for raising an issue! I'm not completely sure what you're after here, as `transform` allows you to make a new column that's the result of some string operations. For example,

```python
In [17]: d = Data([('a', 1), ('b', 2), ('c', 3)], dshape='1 * {a: string, b: int}')

In [18]: d.a.map(lambda x: x.upper() + 'B', 'string') + 'c'
Out[18]:
     a
0  ABc
1  BBc
2  CBc

In [19]: transform(d, f=d.a.map(lambda x: x.upper() + 'B', 'string') + 'c')
Out[19]:
   a  b    f
0  a  1  ABc
1  b  2  BBc
2  c  3  CBc

In [20]: transform(d, f=d.a + d.a + 'B')
Out[20]:
   a  b    f
0  a  1  aaB
1  b  2  bbB
2  c  3  ccB
```

**Comment by cpcloud** [comment]
This will of course be backend dependent.

**Comment by cpcloud** [comment]
@bittlingmayer You may need to update blaze odo and datashape to get this functionality

**Comment by bittlingmayer** [comment]
@cpcloud Thanks for taking a look

Updating *blaze* did the trick, as far as supporting `+` / `_add` for string fields.

I'm afraid that my example oversimplified what I would like to do.  In fact I would like to send the values of 2 columns to an external lib that takes 2 arguments, and write it back to a new column.

The way that I see to achieve this currently is
```
d = transform(d, tmp=d.x + SEP + d.y)

def fn(x):
    x, y = x.split(SEP)
    return call_to_an_external_lib(x, y)

d.tmp.map(fn, 'string')
```
It works, but is far from ideal (especially if we want larger or dynamic column sets, or mixed types).

Maybe I am doing something wrong, or simply out of the scope of Blaze?

**Comment by cpcloud** [comment]
@bittlingmayer you can select out your columns first and then run map on that with a function of multiple arguments, like so:

```python
In [12]: from blaze import Data

In [13]: d = Data(pd.DataFrame([[1,2,3],[3,4,5],[5,6,7]],columns=list('abc')))

In [14]: d
Out[14]:
   a  b  c
0  1  2  3
1  3  4  5
2  5  6  7

In [15]: d[['a', 'b']].map(lambda x, y: x + y, 'int64')
Out[15]:

0   3
1   7
2  11
```
