### ISSUE TITLE
Data('file.csv') no longer infers fields with string values

### ISSUE THREAD

**Issue by bittlingmayer** [blaze/blaze#1254]
On 0.8.0 this worked.  But since I updated, instantiating Data from a .csv is broken in cases like the following:

```
x,tl,z
Be careful driving.,hy,en
Be careful.,hy,en
Can you translate this for me?,hy,en
Chicago is very different from Boston.,hy,en
Don't worry.,hy,en
```
Actual vs expected output:
```
Data('data/broken.csv').fields
['0', '1', '2']
Data('data/works.csv').fields
[u'x', u'tl', u'z']
```

If the values are numbers, then it is inferred correctly:
```
x,tl,z
Be careful driving.,1,en
Be careful.,12,en
Can you translate this for me?,2,en
Chicago is very different from Boston.,2,en
Don't worry.,2,en
```

If the column name is 'y', then it is also inferred as expected:
```
x,y,z
Be careful driving.,hy,en
Be careful.,hy,en
Can you translate this for me?,hy,en
Chicago is very different from Boston.,hy,en
Don't worry.,hy,en
```

So it's very sensitive.

**Comment by bittlingmayer** [comment]
It would be nice if we could pass an argument to force the first row to be interpreted as column names.  (I'm sure the underlying CSV parser implementation supports it.)

**Comment by bittlingmayer** [comment]
http://blaze.pydata.org/en/latest/csv.html#correcting-csv-dialects states: *In the first case of incorrect guessing of CSV dialect (e.g. delimiter) Blaze respects and passes through all keyword arguments to pandas.read_csv.*

However
```
Data('data/broken.csv', header=0).fields
['0', '1', '2']
```

Moreover, pandas infers the fields as expected:
```
pandas.read_csv('data/broken.csv').columns
Index([u'x', u'tl', u'z'], dtype='object')
```

So for now the workaround is `Data(pandas.read_csv('data/broken.csv'))`.

**Comment by cpcloud** [comment]
@bittlingmayer Pass `has_header=True` to the `Data` constructor:

```python
d = Data('foo.csv', has_header=True)
```

**Comment by cpcloud** [comment]
I'm going to add a test and a bit of documentation for this issue and then close it

**Comment by bittlingmayer** [comment]
Documentation would be good, although I also think the original ie pandas behaviour is a bit smarter.

**Comment by cpcloud** [comment]
@bittlingmayer Yes, it's smarter, however this is a compromise between being explicit and convenience
