### ISSUE TITLE
Can't import blaze on Windows 7 after `conda install blaze`

### ISSUE THREAD

**Issue by zygmuntz** [blaze/blaze#1276]
In [1]: import blaze
	---------------------------------------------------------------------------
	AttributeError                            Traceback (most recent call last)
	<ipython-input-1-5c5ee3cb747a> in <module>()
	----> 1 import blaze

	c:\usr\anaconda\lib\site-packages\blaze\__init__.py in <module>()
		 16
		 17 from datashape import dshape, discover
	---> 18 from .utils import ignoring
		 19 from .expr import (Symbol, TableSymbol, symbol, ndim, shape)
		 20 from .expr import (by, count, count_values, distinct, head, join, label, like,

	c:\usr\anaconda\lib\site-packages\blaze\utils.py in <module>()
		 24 from .dispatch import dispatch
		 25
	---> 26 thread_pool = ThreadPool(psutil.cpu_count())
		 27
		 28

	AttributeError: 'module' object has no attribute 'cpu_count'

**Comment by llllllllll** [comment]
Which version of python are you running?

**Comment by zygmuntz** [comment]
Python 2.7.5 |Anaconda 1.8.0 (64-bit)| (default, Jul  1 2013, 12:37:52) [MSC v.1500 64 bit (AMD64)]

**Comment by llllllllll** [comment]
Which version of psutil do you have installed? I remember that this API was changed recently. I am not sure why you would have a mismatched version; however, I don't use conda so I am not sure how dependencies are resolved.

**Comment by zygmuntz** [comment]
psutil                    1.1.2                    py27_0

**Comment by llllllllll** [comment]
I think we are using a much newer version of this, I am on `3.1.1`. Could you try upgrading the package? The conversion is pretty simple if you are using the older API in other parts of your app, I can try to dig up the commit where we upgraded

**Comment by zygmuntz** [comment]
That solves the problem, thank you. Strange that psutil didn't get upgraded automatically when installing blaze, maybe you should look into that.
