### ISSUE TITLE
OperationalError on everything I run

### ISSUE THREAD

**Issue by ThaWeatherman** [blaze/blaze#1287]
Connected to a Hive instance, and trying to run `data.count()` where `data = blaze.Date('hive url')`. I get the following: http://pastebin.com/Gmx30xcE.

Changing it to

```
nrows = data.count()
res = int(nrows)
```

yields a different OperationalError: http://pastebin.com/zfUcML5d.

If anyone could help me out with this it would be fantastic.

**Comment by mrocklin** [comment]
Looking at the error message it looks like your node memory sizes are very very small.  It looks like blaze is correctly generating the queries to send to hive, but that hive itself is crashing.

```
Container [pid=4130,containerID=container_e01_1445988322687_0013_01_000002] is running beyond physical memory limits. Current usage: 195.9 MB of 170 MB physical memory used; 1.7 GB of 357.0 MB virtual memory used. Killing container
```

You might want to use nodes that have more than 170MB of physical memory or configure Hive to use far less memory per node.  It looks like it would appreciate at least a couple gigabytes.

**Comment by cpcloud** [comment]
This isn't really a blaze issue. Closing.
