### ISSUE TITLE
sqlite backend features missing with in-memory db

### ISSUE THREAD

**Issue by thpfaff** [blaze/blaze#1326]
I'm trying to create and access a sqlite in-memory database with blaze

When I try the following code:
```python
import random
import sqlite3
import pandas
import blaze

data = {name: [random.randint(0, 10) for _ in range(10000)] for name in ['ab', 'cd', 'ef']}

con = sqlite3.connect(':memory:')
# con = sqlite3.connect('test.sqlite')

df = pandas.DataFrame(data)
df.to_sql('test', con, if_exists='replace')
con.commit()

bl = blaze.Data('sqlite:///:memory:')
# bl = blaze.Data('sqlite:///test.sqlite')
print(repr(bl.test))
```

I get an error
`AttributeError: 'InteractiveSymbol' object has no attribute 'test'`

If I use the commented out file-version, the code runs without problems

**Comment by cpcloud** [comment]
This is consistent with how the `sqlite3` command prompt works *and* how sqlalchemy works. If you type `sqlite3` in the shell and start executing DDL command you won't see the results of those commands in another `sqlite3` prompt. If you fire up two engines using sqlalchemy with the URL `'sqlite://'` then you get two distinct in-memory connections.

**Comment by cpcloud** [comment]
Odo does happen to cache in memory connections, but this behavior is probably going to go away soon (https://github.com/blaze/odo/pull/328) because it prevents passing in keyword arguments that are critical for certain dialects

**Comment by thpfaff** [comment]
Thanks for the hint.
Using the same sqlalchemy engine in both cases works. (omitting imports and data generation from above)

```python
import sqlalchemy

engine = sqlalchemy.create_engine('sqlite://')

df = pandas.DataFrame(data)
df.to_sql('test', engine, if_exists='replace')

bl = blaze.Data(engine).test

print(repr(bl))
```

**Comment by cpcloud** [comment]
@thpfaff Thanks for the question, and happy to help!
