### ISSUE TITLE
Labels for reduction expressions

### ISSUE THREAD

**Issue by pratapvardhan** [blaze/blaze#1332]
Currently, arguments for grouping are defined like

```python
by(grouper, name=reduction, name=reduction, ...)
```
example
```python
by(d.species, avg=d.petal_length.mean())
```

Is there a way to define aliasname for reductions using labels like
```python
by(grouper, reduction.label('name'), reduction.label('name'), ...)
```
```python
by(d.species, d.petal_length.mean().label('avg'))
```

reason being, I'd like to dynamically construct the multiple reductions and alias names are strings in this case.

**Comment by llllllllll** [comment]
You can `**` unpack the dict like:
```python
my_reductions = {...}
by(grouper, **my_reductions)
```

**Comment by pratapvardhan** [comment]
@llllllllll -- perfect, that works, I was naively stuck with populating list (working in sqlalchemy mode).

Thanks for this, I'll keep this open for few hours, while I test it out.
