### ISSUE TITLE
Blaze not loading HTTP data

### ISSUE THREAD

**Issue by ltransom** [blaze/blaze#1336]
Blaze will not compute on data associated with a RESTful service, although it will properly query the data to get the data shape.

In the attached script, Blaze will hit the REST endpoint and display the data shape, but the compute fails.

```python
from blaze import Data, compute

bdf = Data("http://real-chart.finance.yahoo.com/table.csv?s=%5EGSPC&a=00&b=1&c=2014&d=11&e=31&f=2014&g=d&ignore=.csv")

# will print the datashape for the endpoint
print(bdf.dshape)

# will produce and error
print(compute(bdf))
```

**Comment by kwmsmith** [comment]
Closed by #1354.
