### ISSUE TITLE
Get min of a column / compute blaze.expr.reductions.min

### ISSUE THREAD

**Issue by scls19fr** [blaze/blaze#1367]
Hello,

I would like to get the min of a column using Blaze.

It works fine inside IPython (in fact it displays nice) but I don't know how to make it works in a script.

    In [1]: ds = bz.Data(table_uri)

    In [2]: ds['Date'].min()
    Out[2]: datetime.datetime(2013, 3, 25, 0, 0)

In fact I noticed that

    In [151]: type(ds['Date'].min())

returns

    Out[151]: blaze.expr.reductions.min

How to make this work in a script as I'm expecting (returning a datetime ?)

    print(ds['Date'].min())

displays

    min(_1.Date)

I tried this

    bz.compute(ds['Date'].min())

but I'm getting inside IPython

    <sqlalchemy.sql.selectable.Select at 0x102ab6dd8; Select object>

and in a script I get

    SELECT min(`OHLCV_D_YAHOO_F`.`Date`) AS `Date_min`
FROM `OHLCV_D_YAHOO_F`

Any help ? because I don't feel very confortable with SQLAlchemy.

Maybe this could be add to http://blaze.readthedocs.org/en/latest/rosetta-pandas.html

Kind regards

PS: I notice a very odd behavior:

    In [5]: ds['Date'].min() + datetime.timedelta(hours=1)
    Out[5]: 20130325001970.0

**Comment by kwmsmith** [comment]
Hello @scls19fr,

Thanks for taking the time to post an issue.

This is a common source of frustration for new users and we're working to make this part of Blaze more straightforward and better documented.

The short answer to your question, under the current API, is to `odo()` your result into a `datetime` object:

```
In [1]: ds = bz.Data(table_uri)

In [2]: from datetime import datetime

In [2]: odo(ds['Date'].min(), datetime)
Out[2]: datetime.datetime(2013, 3, 25, 0, 0)

In [3]: type(_) # an actual datetime object
Out [3]: datetime.datetime
```

This approach will work either in an interactive session or in a script, with the same code.

Again, we're working to make this more approachable and less confusing in coming releases, and we'll be improving the docs to reflect these improvements as well.

I made your P.S. note into a separate issue: #1368.

**Comment by scls19fr** [comment]
Thanks @kwmsmith for your reply... but there is still a problem for me with your solution...

I have to know that this column contains `datetime` !

So it lacks the dynamic approach of Python.

Isn't there a way to get a `datetime` (in my case) without saying I want a `datetime` ?

because

    odo(ds[column].min(), datetime)

will fail if `column` contains for example `float`

**Comment by llllllllll** [comment]
blaze is not really designed to work without knowing the types of things. One of the major benefits of the blaze expression system is that you can know the shape and type of the expression you are working with before computing it. If you really want to be dynamic here, you could do:

```python
compute(expr).scalar()
```

To execute your sqlalchemy expression (which you are assuming to be a scalar expression) and then return the python type that maps to the sql type.

**Comment by scls19fr** [comment]
Thanks @llllllllll
