### ISSUE TITLE
Special case InteractiveSymbol in expr.core.isidentical()

### ISSUE THREAD

**Issue by kwmsmith** [blaze/blaze#1375]
Consider changing the order of checks in

https://github.com/blaze/blaze/blob/master/blaze/expr/core.py#L56-L57

to handle `InteractiveSymbol`s as a special case.  Since the `data` attribute on an InteractiveSymbol can be arbitrarily large, doing an equality check on `.data` can be expensive.  Do the inexpensive tests first--`dshape` and `name`--then the potentially expensive one.

https://github.com/blaze/blaze/blob/master/blaze/interactive.py#L78

**Comment by llllllllll** [comment]
I have an open pr that removes this function entirely
