### ISSUE TITLE
Remove `Table`, `TableSymbol` and related?

### ISSUE THREAD

**Issue by kwmsmith** [blaze/blaze#1430]
`Table` has been [deprecated](https://github.com/blaze/blaze/blob/master/blaze/interactive.py#L150-L154) for some time.  The deprecation message points users to `Data` instead.

Unless there are usecases that can't be converted to use `Data` (or `data`), we will be removing `Table`, `TableSymbol`, their tests, and updating the docs in 0.10.

It appears that most of the work will involve a documentation update.

**Comment by kwmsmith** [comment]
Closed by #1441.

**Comment by llllllllll** [comment]
:recycle:
