### ISSUE TITLE
Style for long explicit import lists

### ISSUE THREAD

**Issue by kwmsmith** [blaze/blaze#1432]
Quoting @llllllllll in a PR thread:

>  I have a style request: can we put parenthesized imports on their own lines sorted alphabetically like:

> ```
from a import (
    b,
    c,
)
```

> I have been updating these as I see them. The reason I prefer this style is that it makes it very easy to trace imports visually and understand where names are coming from. As it is now it is hard to quickly see what names are available, or the fact that sum is being aliased here.

> If you have strong feeling about this please let me know.

Thanks for bringing this up.

## Breaking out imports one per-line

I see the value of breaking out the imports one-per line, but there are tradeoffs that should be considered, and there's the overall style whether we have hanging indents, etc.

For a file with not many explicit imports--a couple dozen or so--this approach makes perfect sense.  +1 alphabetization as well.

If we have a source file with a lot of explicit imports, then we could end up with 50 or more lines devoted to imports if we break things up one per line.  I don't want to devote that much vertical real-estate to imports, especially since it's easy to use code editor search to quickly see if and where something is imported at the top.  So if there are a lot of explicit imports, then I'm -1 on breaking things up too much to conserve vertical space.

If we have an `__all__` declaration at the top of a file and there are many elements in the list, I'm fine with breaking them out one per line, since this makes it very clear what the module is exposing publicly.

## General indentation style

On this point, I want to move Blaze over time to the dask indentation style.  I've started a branch to integrate flake8 checking in Blaze to check for common style things to make it easy to have a consistent style checker.  I suggest that once I get that PR ready we discuss on that thread.

**Comment by llllllllll** [comment]
What is the cost of using a lot of space for imports? Editors will be able to handle sparse and dense code the same; however, the humans reading it will not.

About flake8: I normally use this but disagree with a few of the points it complains about. We will definitly need to supress the warning that it emits about redefining an unused function because of all of the multiple dispatch code. One that I personally disagree with is code like:

```python
if (some_long_boolean_expression and
    some_other_bollean_expression):
    # comment explaining the long condition you just wrote
    <body>
```
This is backed up in the pep8 document:

>  When the conditional part of an if -statement is long enough to require that it be written across multiple lines, it's worth noting that the combination of a two character keyword (i.e. if ), plus a single space, plus an opening parenthesis creates a natural 4-space indent for the subsequent lines of the multiline conditional. This can produce a visual conflict with the indented suite of code nested inside the if -statement, which would also naturally be indented to 4 spaces. This PEP takes no explicit position on how (or whether) to further visually distinguish such conditional lines from the nested suite inside the if -statement. Acceptable options in this situation include, but are not limited to:

```python
# No extra indentation.
if (this_is_one_thing and
    that_is_another_thing):
    do_something()

# Add a comment, which will provide some distinction in editors
# supporting syntax highlighting.
if (this_is_one_thing and
    that_is_another_thing):
    # Since both conditions are true, we can frobnicate.
    do_something()

# Add some extra indentation on the conditional continuation line.
if (this_is_one_thing
        and that_is_another_thing):
    do_something()
```

Also, what is dask indentation?

**Comment by llllllllll** [comment]
Another thing this makes easy is git merges where people have added or removed imports.

**Comment by postelrich** [comment]
I'm in favor of alphabetizing but one per line seems excessive.

Also curious what is dask indentation?

**Comment by llllllllll** [comment]
The reason I care so much about this is that literally earlier today I had to rebase where someone had changed an import in a list and git couldn't merge because the imports were all jumbled on the same line. I also had trouble visually diffing the lists because they were all jumbled together.

**Comment by kwmsmith** [comment]
@llllllllll what are your thoughts on importing modules with shortened aliases, and just using namespaced access / lookup?

So something like:

```
from ..expr import (Projection, Field, Broadcast, Map, Label, ReLabel,
                    Merge, Join, Selection, Reduction, Distinct,
                    By, Sort, Head, Sample, Apply, Summary, Like, IsIn,
                    DateTime, Date, Time, Millisecond, ElemWise,
                    Symbol, Slice, Expr, Arithmetic, ndim, DateTimeTruncate,
                    UTCFromTimestamp, notnull, UnaryMath, greatest, least)
```

Would become:

```
from .. import expr as bexpr

# ...

bexpr.Projection(...)
bexpr.Field(...)
# etc.
```

The advantage as I see it is that it gives a clear namespace for a module with many imports; when looking at code inside `blaze.compute.python`, it's always clear what symbol comes from where without having to search the `import` statements at the top of the file.  The downside is more verbosity in the module body itself.  I'm on the fence here, just curious your thoughts.

> The reason I care so much about this is that literally earlier today I had to rebase where someone had changed an import in a list and git couldn't merge because the imports were all jumbled on the same line. I also had trouble visually diffing the lists because they were all jumbled together.

I hear you, and I see the benefit from a tooling / git merging point of view.  But the tradeoff comes with regards to readability, vertical real estate, etc.  How often is it the case that the one thing preventing an automatic merge is import statement changes?  Whenever I have to resolve a merge conflict it's almost always in the body of some code block *as well as* imports, so I'm not 100% convinced that breaking up imports is an unambiguous win here from a git merge point-of-view.

Overall, I don't think our code style should be optimized for tooling (git merging, code searching); at the end of the day, "readability counts", and the code should be optimized for readability--this is Python, after all.  I realize how subjective that is, and I don't want ridiculously rigid rules around style that grate on people, but I also don't want a schizophrenic codebase where we have widely varying coding styles jostling with each other.

> Also, what is dask indentation?

Yes, I should have given more details on what I mean here.  This is also the Pandas indentation style, and the Numpy style (more or less).

Basically, it comes down to how to indent nested things--data structure literals, nested function calls, function calls and function definitions with long argument lists, etc.

For example, this is the style I'm referring to from PEP8:

```python
foo = long_function_name(var_one, var_two,
                         var_three, var_four)
```

Something more non-trivial:

```python
somedict = {'a': some_function_call(arg1='...', arg2='...',
                                    arg3='...', arg4='...'),
            'b': ['a longish string',
                  'another longish string',
                  'a third longish string',
                  'etc, etc, etc'],
            'c': another_func_call(nested_func_call(arg1, arg2,
                                                    arg3, arg4)),
            'd': dict(dict_var1='...',
                      dict_var2='...',
                      etc='...')}
```

Some things to point out are as follows:
* closing delimiters--parens, brackets, curlies--don't hang on their own line;
* no linebreak immediately after an opening curly, paren, or bracket;
* for nested things that are broken over two or more lines, the nested indentation is such that there is vertical alignment within its associated scope (it's hard to put this into words precisely);
* if things get too nested and pushed too far towards the right margin, then define a local variable to help remove nesting levels.

This is to be distinguished from what I'd call "C-style" Python, for lack of a better name:

```python

foo = long_function_name(
    var_one, var_two,
    var_three, var_four
)

somedict = {
    'a': some_function_call(
            arg1='...', arg2='...',
            arg3='...', arg4='...'
         ),
    'b': [
            'a longish string',
            'another longish string',
            'a third longish string',
            'etc, etc, etc',
         ],
    'c': another_func_call(
            nested_func_call(
                arg1, arg2,
                arg3, arg4
            )
         ),
    'd': dict(
            dict_var1='...',
            dict_var2='...',
            etc='...'
        )
}
```

I call it "C-style" due to the closing parens, curlies, and brackets on their own lines, indented to indicate block structure for literals and function calls, similar to how C and C++ code have closing curlies on their own line to indicate the close of a block.

Quickly glancing at some PyData codebases, Dask, Pandas, and NumPy use the first style for the majority of their code.  This is the style that I'm promoting for Blaze.  Blaze currently has both styles in the codebase in more or less equal proportion, which is jarring.  I want one style.

I realize this gets into aesthetics, and I specifically do not want to go down the road of debating the relative merits of either style, there are pros and cons to both.

I also don't want to have rigid rules in place that strictly enforce a style -- this is more of a guideline, that over time, the style is gradually made more consistent.

**Comment by llllllllll** [comment]
I am in support of importing modules and late binding names. I do this with numpy, pandas and even blaze (`import blaze as bz`). imho is the is the best solution for call site readability and does not have us fighting over the import list format. We could say > 8 or so lines of imports and you should just use a qualified name.

Regarding the indentation style: I pretty strongly prefer the second style. The numpy-style leaks so much horizontal space. This makes it more frustrating to rename functions because I need to reindent everything and cannot just automatically rename. The big hidden cost is that people will prefer less descriptive names because they need to preserve their indents. People should choose appropriatly long names to describe a function, class, or datum but instead they will shorten in strange ways like the C stdlib (like `vsnprintf`). Normalizing the nesting make the structure of the function call / literal very clear at a first glance. I would go even farther than you did and put every element on its own line like:

```python
function(
    arg0,
    arg1,
    kw0=a,
    kw1=b,
)
```

imho vertical space is free, breaking things up helps us read and change the code later.

**Comment by kwmsmith** [comment]
> About flake8: I normally use this but disagree with a few of the points it complains about. We will definitly need to supress the warning that it emits about redefining an unused function because of all of the multiple dispatch code.

Yes, I'm actually only interested in a select few things from flake8.  More specifically, as a first cut, I think we should turn off almost everything from pep8, and keep just a few flake8-specific checks.  And yes, we'll definitely need to turn off function redefinitions, for the reason you mention :)

In the WIP flake8 branch, I've turned off all pep8 checks, and enabled only a few core things.

**Comment by kwmsmith** [comment]
> I am in support of importing modules and late binding names. I do this with numpy, pandas and even blaze (import blaze as bz). imho is the is the best solution for call site readability and does not have us fighting over the import list format. We could say > 8 or so lines of imports and you should just use a qualified name.

Agreed.

> Regarding the indentation style: I pretty strongly prefer the second style. The numpy-style leaks so much horizontal space.

It's funny you put it that way -- my aesthetic criticism of the "C-style" is that it leaks so much vertical space :), and it makes it harder for me to read and know what scope things belong to.

For instance:

```python
descriptive variable name = [
    some_long_function_call(
        arg1,
        arg2,
        arg3,
    ) 
    for arg1 in range(
        var1 * var2 + var3,
        1000,
        3,
    )
]
```

It splats everything out over so many lines, it's hard to see at first glance that it's a listcomp, and how it parses out.  The groupings are strange, since `some_long_function_call` is the first thing in the listcomp, but it's formatted to look like it belongs to `descriptive_variable_name`; also, the arguments to `range` look like they belong to the `for arg ...`, and I have to look to realize that block is the argument list to `range`.  I find this very difficult to read, although I'll grant that readbility is a subjective thing.  With the extra vertical spacing, it also limits the amount of code that can be fit on one screen, which becomes an annoyance when you have just 70 lines or so visible at a time.

I'm much more in favor of:

```python

descriptive variable name = [some_long_function_call(arg1, arg2, arg3)
                             for arg1 in range(var1 * var2 + var3, 1000, 3)]
```

I'm willing to put in the effort to keep the horizontal spacing consistent to make clear the grouping and scoping.  With editor tools, I don't find the horizontal spacing updates after renames onerous.

If I can find an automatic code reformatter that reformats things the way I'm advocating here, would that help to allay your issues with tooling?

I also see it as an extension of Python's philosophy around whitespace and indentation in general: indentation should be the primary way to communicate scoping, not delimiters.  Putting delimiters on their own lines pulls things towards a more block-centric style, like C, C++, Ruby, Fortran, etc.  I admit this is very subjective.

I think the "C-style" optimizes for tooling at the expense of vertical whitespace and readability.  The "Numpy-style" has more of a focus on (an admittedly subjective sense of) readability at the expense of horizontal whitespace.  Unfortunately we come down on opposite sides :)

I think we should agree to disagree here since there's no objective criteria to say "this style is better than that style".  Since PEP-8 leaves this an open question, we have to make a call in favor of one over the other.

Like I said, I really don't want to have a schizophrenic codebase, but I'm fine if we gradually move things towards consistency.

**Comment by llllllllll** [comment]
I find it harder to read but I am not sure it realistically affects my productivity. I also don't really mind having multuple styles in the code base for this reason. If you feel more strongly about the indentation than I do then I don't mind switching styles.

**Comment by kwmsmith** [comment]
Thanks for the discussion; closing.
