### ISSUE TITLE
Questions on `compute_down`

### ISSUE THREAD

**Issue by kwmsmith** [blaze/blaze#1437]
I'm implementing an (internal) backend for Blaze, and I want to intercept all `Selection`, `Projection`, and `Join` expressions when computed against a new type of data.  `compute_down` seems to be the logical choice here, except that it's not triggered when I want when `compute`ing an expression.

This works fine:

```python
s = bz.symbol('s', 'var * {a: int32, b: string}')
e = s[s.a > 100]
bz.compute(e, my_custom_backend_type)
```

Because `e` is a `Selection` object, `compute` dispatches to my `compute_down` implementation, and all is well.

Adding a simple `sort` breaks things, however:

```python
sorted_e = s[s.a > 100].sort('a')
bz.compute(sorted_e, my_custom_backend_type)
```

From tracing the code, to compute `sorted_e`, Blaze first checks for a `compute_down` implementation for `Sort` against the custom backend type in `top_then_bottom_then_top_again_etc()`.  Since that isn't implemented, Blaze then calls `bottom_up_until_type_break(...)`, which descends all the way to the leaf terms and computes them before computing their parents.  Only if there is a type break will Blaze re-compute from the top level again, providing an opportunity to dispatch the `Selection` `compute_down` implementation.  That never happens.

For this backend, I need to always compute `Selection`, `Join`, and `Projection` *before* their subterms.  What I want Blaze to do, is to try calling `compute_down` while walking the expression tree in `bottom_up_until_type_break`, and if it can sucessfully dispatch to `compute_down`, then return that result right away.  That would ensure that my `compute_down` implementations are always triggered before their subterms, which is what I need here.

Some questions:
* is there another way to accomplish what I'm after here that doesn't involve `compute_down`?
* my concern is that adding a call to `compute_down` inside `bottom_up_until_type_break` may break existing backends.  I can experiment with this to see.  Is there a fundamental flaw in this approach?

**Comment by llllllllll** [comment]
This is all consistent. we only compute down at the start or after a type change. You can use optimize to replace these nodes with a custom subclass that tracks the other type of data. This is very close to what we do with `SimpleSelects`

**Comment by kwmsmith** [comment]
@llllllllll I accidentally hit "comment" before finishing my (long winded) post -- could you look at the rest of it and let me know your thoughts?

Thanks.

**Comment by llllllllll** [comment]
Ah, what I would do is have compute_up for that node return a box type such that it forces the compute_down implementation to get called, for example:

```python
@dispatch(Selection, ndarray, ndarray)
def compute_up(expr, arr, pred, **kwargs):
    return Box(expr, arr, pred)


@dispatch(Selection, Box)
def compute_down(expr, box, **kwargs):
    ...
```


does this do what you want it to?

**Comment by kwmsmith** [comment]
@llllllllll thanks, that makes sense, but unfortunately it doesn't fit our usecase.

Almost every instance of `compute_down` dispatches on the `Expr` base type and a specific data type.  This works well for type-specific dispatching, since blaze's `compute` logic will break whenever there's a type change, which re-triggers `compute_down`.

But it doesn't work well when we want to dispatch on specific `Expr` subclasses.  For these cases, `compute_down` has to  traverse the expression tree manually and make the node substitutions.  This feels broken to me, since we're re-implementing tree traversal in many places.

In our usecase, with `Selection`, we specifically do not want blaze to compute the predicate before we have a chance to analyze it.  I'd rather not traverse the whole expression tree in `compute_down` to find all `Selection`s; I'd rather let the core `compute` logic handle tree traversal for me.

In your example, `compute_up` will hit `Selection` after the selection's predicate is already computed.  We specifically don't want this behavior.

We can get around this by dispatching on `Expr, CustomType, CustomType` and walk the expression tree ourselves to intercept the `Selection` nodes before their predicates are computed.

But it feels weird to have to reimplement tree-traversal logic in several places; it feels like, from a design point of view, Blaze's `compute` infrastructure should be pretty much the only place where tree traversal logic goes, unless there are very special cases to handle.

This also comes up in `blaze.cached.CachedDataset`: it ends up being pretty much useless.  It only works when computing the exact same expression against the cache; if computing a new expression based on a cached expression, the underlying cached dataset isn't used at all, leading to expensive re-computation.

This is another case where, if blaze called `compute_down` while walking down the expression tree, then it would be much more useful, since we would have an opportunity to insert the cached result as high up in the expression tree as possible.

I'll play with tweaking the `compute_down` logic in `bottom_up_until_type_break` to see how badly my proposed changes will break existing code.  That will help determine what I'm thinking will work or not.  If things break badly, then I'll probably try another route.

**Comment by llllllllll** [comment]
If you want the exact case of not computing the predicate before the table then this already exists in `blaze.expr.optimize.simple_selections`. An example usage of this is in the mongo backend. The only concerns I have with calling compute down at every step is performance, but that is not that big because I am mainly using blaze with postgres with non-trivial queries that dominate the runtime, but also that it blurs the distinction between compute_down and optimize.

**Comment by kwmsmith** [comment]
@llllllllll Thanks for your explanations; I was able to implement what I needed without resorting to changing the core compute logic.

**Comment by llllllllll** [comment]
Awesome!
