### ISSUE TITLE
compute return_type doesn't coerce type

### ISSUE THREAD

**Issue by pratapvardhan** [blaze/blaze#1464]
IIUC, as per #1417,  `bz.compute(return_type=)` - If a type is passed, it will odo the result into the type before returning.

But, that doesn't seem to work with `str`. Here's an example.

```python
In [19]: bz.__version__
Out[19]: '0.10.0rc4+0.g6961844.dirty'

In [20]: data_sql = bz.Data('sqlite:///blaze/examples/data/iris.db::iris')

In [21]: type(bz.compute(data_sql.nrows, return_type=int))
Out[21]: int

In [22]: type(bz.compute(data_sql.nrows, return_type=str))
Out[22]: int
```
`bz.compute(data_sql.nrows, return_type=str)` still returns an `int`.

**Comment by postelrich** [comment]
return_type was added in version 0.10

**Comment by pratapvardhan** [comment]
@postelrich updated the example with '0.10.0rc4+0.g6961844.dirty' version. Issue persists.

**Comment by llllllllll** [comment]
This is hitting a particularly

**Comment by postelrich** [comment]
@llllllllll so this is an odo issue and not the changes to blaze?

**Comment by llllllllll** [comment]
Yeah, it should be the same issue if you do `odo(compute(..., return_type='native'), str)`

**Comment by postelrich** [comment]
should close this and open an odo ticket then?

**Comment by llllllllll** [comment]
That would be great, thanks
