### ISSUE TITLE
expr.fields bug, or intended behavior?

### ISSUE THREAD

**Issue by kwmsmith** [blaze/blaze#1470]
```python
In [1]: import blaze as bz

In [2]: t = bz.symbol('t', 'var * {x: int, y: int}')

In [3]: t.fields
Out[3]: ['x', 'y']

In [4]: t.y.fields
Out[4]: ['y']
```

This makes me think that `.fields` are the column names for the expr's dshape.

```python
In [5]: (t.x + 1).fields
Out[5]: ['x']

In [6]: (t.x + 1 > 10).fields
Out[6]: ['x']

In [7]: (t.x + 1 > 10).dshape
Out[7]: dshape("var * bool")
```

This seems inconsistent: the `dshape` has no named columns, but `.fields` gives back `['x']`.

```python
In [8]: (t.x + t.y).fields
Out[8]: []
```

And then this gives back `[]`, when I'd expect something like `['x', 'y']`--and that's what I'd like `.fields` to give me.

@llllllllll  thoughts?

**Comment by llllllllll** [comment]
See: https://github.com/blaze/blaze/issues/1433

Basically I think `fields` should contain anything that you can do a field access with, or

```python
for f in expr.fields:
    expr[f]
```

**Comment by kwmsmith** [comment]
> Basically I think fields should contain anything that you can do a field access with

OK, that seems consistent.  And it would make these examples invalid, right?

```python
In [5]: (t.x + 1).fields  # Should be []
Out[5]: ['x']

In [6]: (t.x + 1 > 10).fields # should be []
Out[6]: ['x']

In [7]: (t.x + 1)['x'] # should raise exception
Out[7]: t.x + 1
```

**Comment by llllllllll** [comment]
Yeah, I think these should be empty
