### ISSUE TITLE
Methods in the `column.str` namespace

### ISSUE THREAD

**Issue by kwmsmith** [blaze/blaze#1506]
The  kwmsmith/blaze:str-namespace branch has started the work to implement Pandas' `df.column.str.upper()` API in Blaze.

This issue captures the relevant methods and breaks them out approximately according to difficulty.

The initial effort will implement these for Pandas first, and then extend to SQL given time, resources, and overlap with SQL support.

Completed:
* upper
* lower
* cat
* len
* find
* `__getitem__`

Low-hanging:
* isalnum isalpha isdecimal isdigit islower isnumeric isspace istitle isupper 
* reverse
* replace
* capitalize
* pad
* strip / lstrip / rstrip

regex-related (not low-hanging):
* slice_replace
* extract w/ single group

For reference, in both pandas and str:
* capitalize
* center
* count
* encode
* endswith
* find
* index
* isalnum
* isalpha
* isdecimal
* isdigit
* islower
* isnumeric
* isspace
* istitle
* isupper
* join
* ljust
* lstrip
* partition
* replace
* rfind
* rindex
* rjust
* rpartition
* rsplit
* rstrip
* split
* startswith
* strip
* swapcase
* title
* translate
* zfill

In pandas, not in str:
* contains
* decode
* extract
* extractall
* findall
* get
* get_dummies
* normalize
* pad
* repeat
* slice
* slice_replace
* wrap

**Comment by stefanseefeld** [comment]
All but two of the above are part of https://github.com/blaze/blaze/pull/1515.
The two missing ones:
* reverse (should that be added to pandas first ?)
* extract (I need to  look into how to generate a new DataFrame from a single Series)

**Comment by kwmsmith** [comment]
Closing, as the vast majority are now implemented.  Thanks @stefanseefeld
