### ISSUE TITLE
_Data: attribute access fails

### ISSUE THREAD

**Issue by skrah** [blaze/blaze#1529]
In the following example ```hasattr()``` returns ```True```, but the attribute access fails.
The same example works with direct access to a PostgreSQL database.

```
>>> import blaze as bz
>>> import sqlalchemy as sa
>>> 
>>> metadata = sa.MetaData()
>>> s = sa.Table('accounts', metadata,
...              sa.Column('a', sa.Float([4.0, 4.0, 4.0, 29.0])),
...              sa.Column('b', sa.Float([782.0, 300.0, 200.0, 762.0])),
...              sa.Column('c', sa.Float([144.0, 10.0, 1000.0, 224.0])),
...              sa.Column('d', sa.Float([767.0, 20.0, 2000.0, 88.0])))
>>> 
>>> data = bz.data(s)
>>> hasattr(data, 'a')
True
>>> data.a
AttributeError: 'NoneType' object has no attribute 'connect'
```

**Comment by llllllllll** [comment]
This is because we still have computation happening by default in the repr. When you are repring the column it will print the values by executing the sql query. There is no engine associated with the table (`bind=None`) so it cannot compute. You need to pass the connection string to your metadata object, or you can not repr the object. @kwmsmith is there a way to just disable the compute repr?

**Comment by skrah** [comment]
Thanks,  passing the engine works.

**Comment by kwmsmith** [comment]
>  @kwmsmith is there a way to just disable the compute repr?

In 0.11 we will disable compute repring permanently; in the interim you can do:

```python
 In [11]: import blaze.interactive as bi

In [12]: bi.use_new_repr = True

In [13]: import blaze as bz

In [14]: d = bz.data([1,2,3])

In [15]: d
Out[15]: <'list' data; _name='None', dshape='3 * int64'>

In [16]: d.count()
Out[16]: <`count` expression; dshape='int32'>

In [17]: d.count().peek()
Out[17]: 3

In [18]: d.distinct().count()
Out[18]: <`count` expression; dshape='int32'>

In [19]: d.distinct().count().peek()
Out[19]: 3
```

Once the 0.10.2 release is out I'll cut a PR for these changes.
