### ISSUE TITLE
Unicode issue with HDFS

### ISSUE THREAD

**Issue by arita37** [blaze/blaze#1607]
When running , I faced Unicode issues:
`odo(df_pd, 'hdfstore://F://data.h5::/data/')`

In pandas, we can filter it and re-code it.

```
types = df_pd.apply(lambda x: pd.lib.infer_dtype(df_pd.values))
types[types=='unicode']
for col in types[types=='unicode'].index:
   df_pd[col] = df_pd[col].astype(str)
```

Is there a way to do it in Blaze ?

**Comment by llllllllll** [comment]
I believe this issue is just with `odo` so I opened an issue here: https://github.com/blaze/odo/issues/514
