### ISSUE TITLE
PostgreSQL Column Type INTERVAL()  without specifying a precision is not supported

### ISSUE THREAD

**Issue by rueschm** [blaze/blaze#1615]
TypeError: %d format: a number is required, not NoneType at: 

`blaze.data(myTable)` 

Changing the column type to INTERVAL(0) resolves the Error.

Error Stack: 
/usr/local/lib/python3.4/dist-packages/blaze/interactive.py in data(data_source, dshape, name, fields, schema, **kwargs)
    151         dshape = datashape.dshape(dshape)
    152     if not dshape:
--> 153         dshape = discover(data_source)
    154         types = None
    155         if isinstance(dshape.measure, Tuple) and fields:

/usr/local/lib/python3.4/dist-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/usr/local/lib/python3.4/dist-packages/odo/backends/sql.py in discover_sqlalchemy_selectable(t)
    201 def discover_sqlalchemy_selectable(t):
    202     ordering = {str(c): i for i, c in enumerate(c for c in t.columns.keys())}
--> 203     record = list(_process_columns(t.columns))
    204     fkeys = [discover(fkey, t, parent_measure=Record(record))
    205              for fkey in t.foreign_keys]

/usr/local/lib/python3.4/dist-packages/odo/backends/sql.py in _process_columns(columns)
    223     """
    224     for col in columns:
--> 225         (name, dtype), = discover(col).fields
    226         yield str(name), dtype
    227 

/usr/local/lib/python3.4/dist-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/usr/local/lib/python3.4/dist-packages/odo/backends/sql.py in discover_sqlalchemy_column(c)
    195 def discover_sqlalchemy_column(c):
    196     meta = Option if c.nullable else identity
--> 197     return Record([(c.name, meta(discover(c.type)))])
    198 
    199 

/usr/local/lib/python3.4/dist-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/usr/local/lib/python3.4/dist-packages/odo/backends/sql.py in discover_postgresql_interval(t)
    141 @discover.register(sa.dialects.postgresql.base.INTERVAL)
    142 def discover_postgresql_interval(t):
--> 143     return discover(sa.Interval(day_precision=0, second_precision=t.precision))
    144 
    145 

/usr/local/lib/python3.4/dist-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165 
    166         except MDNotImplementedError:

/usr/local/lib/python3.4/dist-packages/odo/backends/sql.py in discover_typeengine(typ)
    164             raise ValueError('Cannot infer INTERVAL type with parameters'
    165                              'second_precision=%d, day_precision=%d' %
--> 166                              (typ.second_precision, typ.day_precision))
    167         return datashape.TimeDelta(unit=units)
    168     if typ in revtypes:

TypeError: %d format: a number is required, not NoneType

**Comment by darthkedrik** [comment]
I took a look at this, this looks like there's an issue with error handling in blaze/odo/backends/sql.py in the discover_typeengine function. Sending an `INTERVAL()` request with no value is supposed to raise a `ValueError` but is hitting a `TypeError` because of how the formatting is handled.

I'd be happy to take a stab at fixing this.
