### ISSUE TITLE
Question: have more than one resources on blaze server

### ISSUE THREAD

**Issue by frbsfri** [blaze/blaze#1631]
I want to run a blaze server which mounts two data sources, one postgreSQL table and one CSV file, but I dont know how can I mount more than one data source on blaze server. 

I have the following code on server side:
```
engine = create_engine('postgresql://user:pass@localhost:5432/mydb')
with engine.connect() as conn:
    metadata=MetaData()
    metadata.bind=engine
    t=Table('t', metadata, autoload=True, autoload_with=conn)
```

```
server=bz.Server(t)
server.run(host='0.0.0.0', port=6363)

```
and in the client side:
```
source =Data('blaze://localhost:6363/')
t=symbol('t', source.dshape)
expr=t[t.color=='K']
result=compute(expr, Data(source))

```
how can I mount another data source like CSV file or another table of the database on the same blaze server? for example:
`csv= Data('.\data.csv', sep=';', has_header=True)
`

**Comment by llllllllll** [comment]
The standard way to do this would be to make the server's resource a dictionary of other resources. For example:

```python
bz.Server({
    'table': t,
    'csv: csv,
})
```

The values of this dictionary should *not* be expressions, just the underlying resource. You can get that from a bound expression with `.data`; in your csv case you could just instantiate an `odo.CSV` object directly.

**Comment by frbsfri** [comment]
Thanks, I appreciate your time. I did what you suggest to create dictionary of resources.
```
engine = create_engine('postgresql://qfsa:123@localhost:5433/mydb')
with engine.connect() as conn:
    metadata=MetaData()
    metadata.bind=engine
    table1=Data(Table('tablename1', metadata, autoload=True, autoload_with=conn))
    table2=Data(Table('tablename2', metadata, autoload=True, autoload_with=conn)
csvfile=Data('.\data.csv', sep=';', has_header=True)
resources={
        'table1': table1,
        'table2': table2,
        'csvfile': csvfile
}

server=bz.Server(resources)
server.run(host='0.0.0.0', port=6360)
```

In client side when I want to access resources and compute the expression on them, I do this:

```
source=Data('blaze://localhost:6360/')['table1']
t=symbol('t', source.dshape)
query=t[(t.color=='K')]
result=compute(query,source)
```

compute cannot resolve table1 data and I get error that  it does not know how to compute. 
But when i use `peek()`:

`result=compute(query,source.peek())` 

then I will get the result of the query but only on the first 10 rows of data..

What is the problem here?

**Comment by llllllllll** [comment]
Do not wrap the values of the dictionary with `Data` (which is deprecated in favor of `data`). For the sql tables, just pass the `Table` object directly. For the `CSV`, replace `Data(...)` with `odo.resource(...)`

**Comment by frbsfri** [comment]
I tried it:

table1=Table('tablename1', metadata, autoload=True, autoload_with=conn)
table2=Table('tablename2', metadata, autoload=True, autoload_with=conn)
csvfile=odo.resource('.\data.csv', sep=';', has_header=True)

 but in client side, again the query cannot be resolved with the same error as before (does not know how to compute). 

> NotImplementedError: Don't know how to compute:
> type(expr): <class 'blaze.expr.expressions.Selection'>

in client side I still use `source= Data('blaze://localhost:6360/')['table1'] ` , do you think this is the problem?

**Comment by llllllllll** [comment]
Can you post the full traceback?

**Comment by llllllllll** [comment]
Also, looking at the snippet you posted: you should be able to use `source` in place of `t`. For example:

```python
t = data('blaze://localhost:6360/')['table1']
query = t[(t.color=='K')]
result = compute(query)
```

**Comment by frbsfri** [comment]
YES, when I did the `compute `directly on `t`, then the problem is solved , now I have the data as output :) 

Thank you ||||||||| 👍

**Comment by frbsfri** [comment]
Hello,

I can do simple queries on each of the data sources now and I get the result back, but I also want to do Join queries on two data sources which have common column named :` id`
I want to do join query between these two tables ( table1, and csvfile): 
`compute(join(table1,csvfile,'id'))` but it tells me that it cannot compute. here is the full `traceback error`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\envs\p3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Miniconda3\envs\p3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "D:/code/Experiment 2/blazeclient.py", line 32, in <module>
    df=compute(join(sheetheight,dzlog,'ullid'))
  File "C:\Miniconda3\envs\p3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "C:\Miniconda3\envs\p3\lib\site-packages\blaze\interactive.py", line 195, in compute
    return compute(expr, resources, **kwargs)
  File "C:\Miniconda3\envs\p3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "C:\Miniconda3\envs\p3\lib\site-packages\blaze\compute\core.py", line 409, in compute
    result = top_then_bottom_then_top_again_etc(expr3, d4, **kwargs)
  File "C:\Miniconda3\envs\p3\lib\site-packages\blaze\compute\core.py", line 187, in top_then_bottom_then_top_again_etc
    "data: %s" % (type(expr3), expr3, scope4))

NotImplementedError: Don't know how to compute:
type(expr): <class 'blaze.expr.collections.Join'>

expr: Join(lhs=_33.table1, rhs=_34.csvfile, _on_left='id', _on_right='id', how='inner', suffixes=('_left', '_right'))

data: {<`_33` symbol; dshape='{  table1: var * {    id: ?int64,    date: ...'>: <blaze.server.client.Client object at 0x000000000D0C0678>, <`_34` symbol; dshape='{  table1: var * {    id: ?int64,    date: ...'>: <blaze.server.client.Client object at 0x000000000F03FE10>}
>>> 
```
Any idea?

Thanks for your time , I'm grateful that you are looking at my problem.

**Comment by frbsfri** [comment]
I solved it by passing datashapes of data sources in the client side, so in client side my code is:

```
table1=Data('blaze://localhost:6363/', dshape_table1)['table1']
csvfile=data('blaze://localhost:6363/', dshape_csvfile)['csvfile']
csvfile=bz.Data(csvfile, dshape1)  
table1=bz.Data(table1,dshape2)

```

**Comment by llllllllll** [comment]
Right now blaze doesn't have a way to join resources in different backends. This means there is no good way to merge the CSV with the table without fetching both into memory. This is a feature we really want but it is a very hard problem to solve in the generic case.

**Comment by frbsfri** [comment]
Thanks for helping me about the issue , Good Luck with your super cool blaze project.
