### ISSUE TITLE
trademark conflict with FICO Blaze Advisor?

### ISSUE THREAD

**Issue by electronwill** [blaze/blaze#1642]
At the docs page https://docs.continuum.io/docs_oss/blaze/ , someone wrote into the feedback form that there is a product called FICO Blaze Advisor, whose trademark might conflict with the Blaze name.

**Comment by postelrich** [comment]
Doesn't look like a conflict as they are two different tools: http://www.fico.com/en/products/fico-blaze-advisor-decision-rules-management-system#overview

**Comment by electronwill** [comment]
Glad to hear it. I'll go ahead and close this issue.
