### ISSUE TITLE
Implicit Joins

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#288]
Joins are powerful computational constructs.  Unfortunately they're not widely understood.  We should leverage semantic information within Table expressions to provide implicit Joins to the user.
### How would this work?

An implicit join might inspect the schema of two interacting tables for shared columns like `name` in the example below

``` Python
A = TableSymbol('{name: string, dollars: int}')
B = TableSymbol('{name: string, euros: int}')

total = A['dollars'] * exchange + B['euros']
```

A query like this might actually produce a computation like the following

``` Python
tmp = Join(A, B, 'name')
total = tmp['dollars'] * exchange + tmp['euros']
```
### Other Projects
1.  This is why people like the Pandas' index.  It provides a natural index on which to perform joins whenever you do any simple operation like `+` or `>` over series.
2.  Datomic uses implicit joins in their implementation of datalog.  Their users seem to appreciate it.
3.  SQL does it to an extent http://stackoverflow.com/questions/44917/explicit-vs-implicit-sql-joins
### Issues
- Do we join on all matching columns?  
- Should we elevate the concept of index to our expression system?
- Are we comfortable assuming that having the same name implies this strong relationship?  If not then how/where do we maintain these relationships?

**Comment by postelrich** [comment]
Closing old issues. Feel free to reopen with up to date info.
