### ISSUE TITLE
Assist Spark users in parsing CSV files

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#367]
The blaze.data layer doesn't compose nicely through HDFS.   As a result we're often stuck writing parse functions explicitly

    rdd = sc.textfile('hdfs://path/to/my/file')
    def parse(line):
         words = line.strip.split(',')
        id, name, balance = words
        return int(id), name, float(balance)

    rdd = rdd.map(parse)
    ... # use blaze as normal

We actually have tools to make this process easier.  `csv.Sniffer` can be used to figure out how to split lines, `discover` can be used on `sc.textfile(...).take(50)` to find the schema.  `sc.textfile(...).mapPartition(partial(coerce, schema)))` can be used to use DyND to do type coercion.  

All of the pieces are there, we just need to hook them up into an interface that is consistent with the rest of Blaze.

**Comment by cpcloud** [comment]
Is this taken care of by `odo`?

```python
from pyspark import SparkContext, SQLContext
from odo import odo
from blaze import Data, by

sc = SparkContext('local[*]', 'app')
sql = SQLContext(sc)
df = odo('iris.csv', sql, name='iris')  # the name of the table for sparksql
d = Data(sql)
```

**Comment by mrocklin** [comment]
In the local csv file case quite likely.  I'm more concerned about the CSV on HDFS case.  This might be a  situation where we leverage the spark data sources api.
