### ISSUE TITLE
Integer column names not working

### ISSUE THREAD

**Issue by mattwescott** [blaze/blaze#380]
When a Table is backed by a DataFrame with integer column names, indexing the columns fails with a confusing error message. The resulting schema appears to be invalid, since DataShape does not currently allow integer column names.

```
t = blaze.Table(pd.DataFrame(data=[0,1], columns=[0]))
t[0]
```

> ---
> 
> TypeError                                 Traceback (most recent call last)
> <ipython-input-75-92bed093b24f> in <module>()
>      1 t = blaze.Table(pd.DataFrame(data=[0,1], columns=[0]))
> ----> 2 t[0]
> 
> /media/extra/kaggle/birds-scipy2014/blaze/expr/table.pyc in **getitem**(self, key)
>     54         if isinstance(key, TableExpr):
>     55             return Selection(self, key)
> ---> 56         raise TypeError("Did not understand input: %s[%s]" % (self, key))
>     57 
>     58     def sort(self, key=None, ascending=True):
> 
> TypeError: Did not understand input: _31[0]

**Comment by cpcloud** [comment]
We can construct these now, but I don't think we can get at the individual columns:

```python
In [24]: d = Data(pd.DataFrame([[1,2]]))

In [25]: d.fields
Out[25]: ['0', '1']
```

**Comment by postelrich** [comment]
Closing old issues. Feel free to reopen with up to date info.
