### ISSUE TITLE
How to handle missing values in HDF5?

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#407]
I have a csv file with potentially missing values

```
csv = CSV('myfile.csv', schema='{name: string, value: ?int}')
```

I'd like to put it into an HDF5 file

```
hdf5 = HDF5('myfile.hdf5', '/data', schema=csv.schema)
```

How should Blaze handle missing values?  Do we raise an error/warning?  Do we translate the sentinels directly?  (is DyND willing to do this?)

No rush on this.  I suspect that @mwiebe might have thoughts.

**Comment by postelrich** [comment]
Closing old issues. Feel free to reopen with up to date info.
