### ISSUE TITLE
10 minutes to Blaze

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#423]
@cpcloud had the suggestion of replicating [10 minutes to Pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html) a medium length demonstration of Blaze's capabilities.  Perhaps we should have something similar.  

The closest thing we have right now is the [quickstart](http://blaze.pydata.org/docs/dev/quickstart.html).  This could probably be improved and extended into something more comprehensive.  

Presumably people could add to this issue with the sorts of things they'd like to see in such a document.  What would have made learning blaze easier for you?  What examples do you keep at hand to demonstrate Blaze to newcomers?  Simple examples are good.

**Comment by postelrich** [comment]
Closing old issues. Feel free to reopen with up to date info.
