### ISSUE TITLE
Relax constraint that `By` must use reductions

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#438]
The typical split-apply-combine operation, `By` has the following form:

    by(t, t.column, t.column.reduction())

In particular the third argument *must* be a reduction.  SQL prefers this but Pandas, non-streaming-Python, and Spark can all handle larger solutions, i.e.

    by(t, t.column, t.sort(key).head(5))

In this case the per-group result is not a full reduction but rather a smaller table.

**Comment by llllllllll** [comment]
closing in favor of: #1294
