### ISSUE TITLE
Improve internal documentation/scripts to update documentation

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#507]
Currently the procedure to upload our documentation is something like the following:

In standard github make-new-branch, issue pull request, workflow

1.  Add new content to `blaze/docs/source/*.rst`

In non-standard, just push to `gh-pages` workflow

2.  `make html` from `blaze/docs/`
3.  `cp -r build/html/` to somewhere safe
4.  `git checkout gh-pages`
5.  `cp -r html-from-master/*` that you put someplace to `docs/latest/`
6.  `git commit -a`
7.  `git push git@github.com:ContinuumIO/gh-pages`
8.  Check http://blaze.pydata.org/ to make sure that changes look nice

This should happen more often, either because we do it more often or because we make it easier for people to do with scripts.

**Comment by cpcloud** [comment]
we're using read the docs which simplifies this process greatly
