### ISSUE TITLE
Compute pool with timeouts for Server

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#543]
If we want Blaze server to back a web service we'll need to be robust to long-running queries.  Two thoughts
1.  Launch compute jobs in separate processes
2.  Have a timeout on those jobs, be willing to kill long-running ones and add more processes to the pool when they die.

This work can happen in isolation from the Blaze server.  Presumably the flask app should call whatever safe/time-limited compute function we create and the flask server should have `threaded=True` set as a default.

**Comment by postelrich** [comment]
Closing old issues. Feel free to reopen with up to date info.
