### ISSUE TITLE
CSV Headers with Spark

### ISSUE THREAD

**Issue by quasiben** [blaze/blaze#593]
We need a method of handling headers in spark and SparkSQL:

```python
t = Table()
col = t.columns[0]
frdd = rdd.filter(lambda line: col not in line)
```

The above would work but is rather smelly
cc: @mrocklin @cpcloud

**Comment by cpcloud** [comment]
Looks like there's a spark package for this http://spark-packages.org/package/12

**Comment by cpcloud** [comment]
I think this is more of an odo issue

**Comment by cpcloud** [comment]
closing in favor of https://github.com/blaze/odo/issues/372
