### ISSUE TITLE
Linear algebra operations

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#923]
We should add abstract operations `Inverse`, `Solve`, `SVD` and possibly others (though not too many others) and connect them up to standard solutions in numpy/scipy.

This work should first happen in something like a new `blaze/expr/linalg.py` file and then as new `compute_up` functions in `blaze/compute/numpy.py`, etc..

**Comment by cdagnino** [comment]
Maybe not related enough, but I think it would be great if Blaze could get a simple Least Squares routine. Even better if it can accommodate a Generalized Least Squares. I looked around and there doesn't seem to be a python package that implements Least Squares for data that doesn't fit into memory. I know there's been some discussions about it in `statsmodels` (see [this google forum thread](https://groups.google.com/forum/#!topic/pystatsmodels/CICsroXZmrs) for instance). Maybe @josef-pkt can say something about this?

Many apologies if I'm just creating noise here....

**Comment by mrocklin** [comment]
I suggest looking at [`dask`](dask.pydata.org/en/latest/) and in particular [`dask.array`](http://dask.pydata.org/en/latest/array.html) in which creating these sorts of operations are fairly easy.

**Comment by cpcloud** [comment]
i think these are out of scope for blaze right now
