### ISSUE TITLE
Scipy.sparse

### ISSUE THREAD

**Issue by mrocklin** [blaze/blaze#924]
We ought to wrap scipy.sparse matrices.  It's important to think about what value we might be able to add here (might not be much.)  There are some things like `into` functions for creating sparse matrices (we'll have to be careful here).  Another, possibly large impact, is use of scipy.sparse matrices as blocks within dask workflows.

Anyway, this should be a useful task for someone getting to know blaze.  Wrapping a backend is usually good practice.

**Comment by cowlicks** [comment]
I have some scipy.sparse experience and can look into this if it has priority.

**Comment by mrocklin** [comment]
I don't yet see an immediate use for this and I don't think we've had many people ask for it.  I'll hunt around and see if I can find issues that I think are more pressing.  Happy to be overridden by @cpcloud if he has thoughts.

**Comment by kwmsmith** [comment]
I'm closing this issue for now based on current lack of interest and prioritization. @cowlicks or others, feel free to re-open if it becomes relevant in the future.
